language: rust
matrix:
    fast_finish: true
    allow_failures:
        - rust: nightly
    include:
        - rust: stable
        - os: osx
          rust: stable
        - rust: beta
        - rust: nightly

sudo: false
dist: trusty

cache:
  apt: true
  directories:
    - target/debug/deps
    - target/debug/build

script:
  - cargo build --verbose
  - cargo test --verbose

notifications:
  email: false
