language: rust
matrix:
    fast_finish: true
    #allow_failures:
    #    - rust: nightly
    include:
        - os: osx
          rust: nightly
          #rust: stable

        #- rust: stable
        #- rust: beta
        - rust: nightly

        # Disable default-tls
        #- rust: stable
        - rust: nightly
          env: FEATURES="--no-default-features"

        # rustls-tls
        #- rust: stable
        #- rust: nightly
        #  env: FEATURES="--no-default-features --features rustls-tls"

        # default-tls and rustls-tls
        #- rust: stable
        #- rust: nightly
        #  env: FEATURES="--features rustls-tls"

        # optional cookies
        #- rust: stable
        - rust: nightly
          env: FEATURES="--features cookies"

        # optional blocking
        #- rust: stable
        - rust: nightly
          env: FEATURES="--features blocking"

        # optional gzip
        #- rust: stable
        - rust: nightly
          env: FEATURES="--features gzip"

        # socks
        #- rust: stable
        #- rust: nightly
        #  env: FEATURES="--features socks"

        #- rust: stable
        #- rust: nightly
        #  env: FEATURES="--features trust-dns"

        # android
        #- rust: stable
        - rust: nightly
          env: TARGET=aarch64-linux-android
          before_install:
            - wget https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip;
            - unzip -qq android-ndk*.zip;
            - android-ndk*/build/tools/make_standalone_toolchain.py --arch arm64 --api 21 --install-dir /tmp/android-toolchain;
            - export PATH=/tmp/android-toolchain/bin:$PATH;
          install: rustup target add "$TARGET"
          # disable default-tls feature since cross-compiling openssl is dragons
          script: cargo build --target "$TARGET" --no-default-features

        # Check rustfmt
        - name: "rustfmt check"
          rust: stable
          env: RUSTUP_TOOLCHAIN="stable"
          install: rustup component add rustfmt
          script: cargo fmt -- --check


        # minimum version
        #- rust: 1.39.0
        #  script: cargo build

sudo: false
dist: trusty

env:
  global:
    - REQWEST_TEST_BODY_FULL=1
script:
  - cargo build $FEATURES
  - cargo test -v $FEATURES -- --test-threads=1
