[package]
name = "reqwest"
version = "0.9.0-pre" # remember to update html_root_url
description = "higher level HTTP client library"
keywords = ["http", "request", "client"]
repository = "https://github.com/seanmonstar/reqwest"
documentation = "https://docs.rs/reqwest"
authors = ["Sean McArthur <sean@seanmonstar.com>"]
license = "MIT/Apache-2.0"
categories = ["web-programming::http-client"]

publish = false # pre

[dependencies]
base64 = "~0.6.0"
bytes = "0.4"
encoding_rs = "0.7"
futures = "0.1.21"
http = "0.1.5"
hyper = "0.12.2"
hyper-tls = "0.3"
libflate = "0.1.11"
log = "0.4"
mime = "0.3.7"
mime_guess = "2.0.0-alpha.4"
native-tls = "0.2"
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.5"
tokio = "0.1.7"
tokio-io = "0.1"
url = "1.2"
uuid = { version = "0.6", features = ["v4"] }

[dev-dependencies]
env_logger = "0.5"
error-chain = "0.10"
serde_derive = "1.0"

[features]
unstable = []


[[example]]
name = "simple"
path = "examples/simple.rs"

[[example]]
name = "form"
path = "examples/form.rs"

[[example]]
name = "async"
path = "examples/async.rs"
required-features = ["unstable"]

[package.metadata.docs.rs]
features = ["unstable"]
