[package]
name = "reqwest"
version = "0.10.0-alpha.0" # remember to update html_root_url
description = "higher level HTTP client library"
keywords = ["http", "request", "client"]
repository = "https://github.com/seanmonstar/reqwest"
documentation = "https://docs.rs/reqwest"
authors = ["Sean McArthur <sean@seanmonstar.com>"]
readme = "README.md"
license = "MIT/Apache-2.0"
categories = ["web-programming::http-client"]
edition = "2018"
autotests = true

publish = false

[package.metadata.docs.rs]
all-features = true

[features]
default = ["default-tls"]

tls = []

default-tls = ["hyper-tls", "native-tls", "tls", "tokio-tls"]
default-tls-vendored = ["default-tls", "native-tls/vendored"]

#rustls-tls = ["hyper-rustls", "tokio-rustls", "webpki-roots", "rustls", "tls"]

blocking = ["futures-channel-preview", "futures-util-preview/io"]

cookies = ["cookie_crate", "cookie_store"]

gzip = ["async-compression"]

#trust-dns = ["trust-dns-resolver"]

[dependencies]
http = "0.1.15"
url = "2.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
base64 = "0.10"
bytes = "0.4"
encoding_rs = "0.8"
futures-core-preview = { version = "=0.3.0-alpha.18" }
futures-util-preview = { version = "=0.3.0-alpha.18" }
http-body = "=0.2.0-alpha.1"
hyper = "=0.13.0-alpha.2"
log = "0.4"
mime = "0.3.7"
mime_guess = "2.0"
percent-encoding = "2.1"
tokio = { version = "=0.2.0-alpha.5", default-features = false, features = ["rt-full", "tcp"] }
tokio-executor = "=0.2.0-alpha.5"
uuid = { version = "0.7", features = ["v4"] }
time = "0.1.42"

# TODO: candidates for optional features

serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.6.1"

# Optional deps...

## default-tls
hyper-tls = { version = "=0.4.0-alpha.2", optional = true }
native-tls = { version = "0.2", optional = true }
tokio-tls = { version = "=0.3.0-alpha.5", optional = true }

## rustls-tls
#hyper-rustls = { version = "=0.18.0-alpha.1", optional = true }
#rustls = { version = "0.16", features = ["dangerous_configuration"], optional = true }
#tokio-rustls = { version = "=0.12.0-alpha.2", optional = true }
#webpki-roots = { version = "0.17", optional = true }

## blocking
futures-channel-preview = { version = "=0.3.0-alpha.18", optional = true }

## cookies
cookie_crate = { version = "0.12", package = "cookie", optional = true }
cookie_store = { version = "0.9", optional = true }

## gzip
async-compression = { version = "0.1.0-alpha.4", default-features = false, features = ["gzip", "stream"], optional = true }

## socks
#socks = { version = "0.3.2", optional = true }

## trust-dns
#trust-dns-resolver = { version = "0.11", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
env_logger = "0.6"
hyper = { version = "=0.13.0-alpha.2", features = ["unstable-stream"] }
serde = { version = "1.0", features = ["derive"] }
libflate = "0.1"
doc-comment = "0.3"
tokio-fs = { version = "=0.2.0-alpha.5" }

[target.'cfg(windows)'.dependencies]
winreg = "0.6"

# wasm

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.25"
wasm-bindgen = "0.2.48"
wasm-bindgen-futures = { version = "", features = ["futures_0_3"] }

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.25"
features = [
    "Headers",
    "Request",
    "RequestInit",
    "Response",
    "Window",
]

[[example]]
name = "blocking"
path = "examples/blocking.rs"
required-features = ["blocking"]

[[test]]
name = "blocking"
path = "tests/blocking.rs"
required-features = ["blocking"]

[[test]]
name = "cookie"
path = "tests/cookie.rs"
required-features = ["cookies"]

[[test]]
name = "gzip"
path = "tests/gzip.rs"
required-features = ["gzip"]

