[package]
name = "reqwest"
version = "0.1.0"
description = "higher level HTTP client library"
keywords = ["http", "request", "client"]
repository = "https://github.com/seanmonstar/reqwest"
documentation = "https://docs.rs/reqwest"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
hyper = { version = "0.9" , default-features = false }
log = "0.3"
native-tls = "0.1"
serde = "0.8"
serde_json = "0.8"
serde_urlencoded = "0.3"
url = "1.2"

[dev-dependencies]
env_logger = "0.3"

[[example]]
name = "simple"
path = "examples/simple.rs"
