[package]
name = "reqwest"
version = "0.9.6" # remember to update html_root_url
description = "higher level HTTP client library"
keywords = ["http", "request", "client"]
repository = "https://github.com/seanmonstar/reqwest"
documentation = "https://docs.rs/reqwest"
authors = ["Sean McArthur <sean@seanmonstar.com>"]
license = "MIT/Apache-2.0"
categories = ["web-programming::http-client"]

[dependencies]
base64 = "0.10"
bytes = "0.4"
encoding_rs = "0.8"
futures = "0.1.23"
http = "0.1.14"
hyper = "0.12.20"
hyper-old-types = { version = "0.11", optional = true, features = ["compat"] }
hyper-tls = { version = "0.3", optional = true }
libflate = "0.1.18"
log = "0.4"
mime = "0.3.7"
mime_guess = "2.0.0-alpha.6"
native-tls = { version = "0.2", optional = true }
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.5"
tokio = { version = "0.1.7", default-features = false, features = ["rt-full"] }
tokio-executor = "0.1.4" # a minimum version so trust-dns-resolver compiles
tokio-io = "0.1"
tokio-threadpool = "0.1.8" # a minimum version so tokio compiles
tokio-timer = "0.2.6" # a minimum version so trust-dns-resolver compiles
url = "1.2"
uuid = { version = "0.7", features = ["v4"] }
hyper-rustls = { version = "0.15", optional = true }
tokio-rustls = { version = "0.8", optional = true }
webpki-roots = { version = "0.15", optional = true }
rustls = { version = "0.14", features = ["dangerous_configuration"], optional = true }

[target.'cfg(not(target_os = "android"))'.dependencies]
trust-dns-resolver = "0.10"

[dev-dependencies]
env_logger = "0.6"
serde_derive = "1.0"

[features]
default = ["default-tls"]

tls = []

default-tls = ["hyper-tls", "native-tls", "tls"]
default-tls-vendored = ["default-tls", "native-tls/vendored"]

rustls-tls = ["hyper-rustls", "tokio-rustls", "webpki-roots", "rustls", "tls"]

hyper-011 = ["hyper-old-types"]

[package.metadata.docs.rs]
all-features = true
