[package]
name = "reqwest"
version = "0.5.1"
description = "higher level HTTP client library"
keywords = ["http", "request", "client"]
repository = "https://github.com/seanmonstar/reqwest"
documentation = "https://docs.rs/reqwest"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
license = "MIT/Apache-2.0"
categories = ["web-programming::http-client"]

[dependencies]
hyper = "0.10.2"
hyper-native-tls = { version = "0.2", optional = true }
log = "0.3"
serde = "0.9"
serde_json = "0.9"
serde_urlencoded = "0.4"
url = "1.2"
libflate = "0.1.3"

[dev-dependencies]
env_logger = "0.3"

[features]
default = ["default-tls"]
default-tls = ["hyper-native-tls"]
