[package]
name = "reqwest"
version = "0.9.0-pre" # remember to update html_root_url
description = "higher level HTTP client library"
keywords = ["http", "request", "client"]
repository = "https://github.com/seanmonstar/reqwest"
documentation = "https://docs.rs/reqwest"
authors = ["Sean McArthur <sean@seanmonstar.com>"]
license = "MIT/Apache-2.0"
categories = ["web-programming::http-client"]

publish = false # pre

[dependencies]
base64 = "0.9"
bytes = "0.4"
encoding_rs = "0.8"
futures = "0.1.23"
http = "0.1.5"
hyper = "0.12.7"
hyper-old-types = { version = "0.11", optional = true, features = ["compat"] }
hyper-tls = "0.3"
libflate = "0.1.11"
log = "0.4"
mime = "0.3.7"
mime_guess = "2.0.0-alpha.6"
native-tls = "0.2"
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.5"
tokio = "0.1.7"
tokio-io = "0.1"
url = "1.2"
uuid = { version = "0.7", features = ["v4"] }

[dev-dependencies]
env_logger = "0.5"
serde_derive = "1.0"

[features]
default = []
hyper-011 = ["hyper-old-types"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docs_rs_workaround"]
