[package]
name = "reqwest"
version = "0.7.3" # remember to update html_root_url
description = "higher level HTTP client library"
keywords = ["http", "request", "client"]
repository = "https://github.com/seanmonstar/reqwest"
documentation = "https://docs.rs/reqwest"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
license = "MIT/Apache-2.0"
categories = ["web-programming::http-client"]

[dependencies]
bytes = "0.4"
futures = "0.1.14"
hyper = "0.11"
hyper-tls = "0.1.2"
libflate = "0.1.11"
log = "0.3"
native-tls = "0.1.3"
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.5"
tokio-core = "0.1.6"
tokio-io = "0.1"
tokio-tls = "0.1"
url = "1.2"
uuid = { version = "0.5", features = ["v4"] }

[dev-dependencies]
env_logger = "0.4"
serde_derive = "1.0"
error-chain = "0.10"

[features]
unstable = []


[[example]]
name = "simple"
path = "examples/simple.rs"

[[example]]
name = "async"
path = "examples/async.rs"
required-features = ["unstable"]
